# Dockerfile para ambiente de desarrollo Rust con Cap'n Proto
FROM rust:1.92-slim-bookworm

# Instalar dependencias del sistema
# - capnproto: compilador de esquemas
# - libcapnp-dev: headers para desarrollo
# - pkg-config, libssl-dev: necesarios para crates como diesel/sqlx y comunicación segura
# - build-essential: para compilación de dependencias nativas
RUN apt-get update && apt-get install -y \
    pkg-config \
    libssl-dev \
    build-essential \
    git \
    wget \
    && rm -rf /var/lib/apt/lists/*

RUN cargo install cargo-tarpaulin

RUN wget https://capnproto.org/capnproto-c++-1.3.0.tar.gz -O /tmp/capnproto.tar.gz && \
    cd /tmp && \
    tar zxf capnproto.tar.gz && \
    cd capnproto-c++-1.3.0 && \
    ./configure && \
    make check && \
    make install && \
    rm -rf /tmp/capnproto.tar.gz /tmp/capnproto-c++-1.3.0

RUN wget https://download.oracle.com/java/25/latest/jdk-25_linux-x64_bin.deb -O /tmp/jdk.deb && \
    apt-get install -y /tmp/jdk.deb && \
    rm /tmp/jdk.deb

#RUN cd /tmp && \
#    git clone https://github.com/capnproto/capnproto-java.git && \
#    cd capnproto-java && \
#    make && \
#    make install
#    rm -rf /tmp/capnproto-java

RUN cd /tmp && \
    git clone https://github.com/vaci/capnproto-java-rpc.git && \
    cd capnproto-java-rpc && \
    make && \
    make install && \
    rm -rf /tmp/capnproto-java-rpc

WORKDIR /app

# El contenedor se mantendrá vivo para desarrollo
CMD ["sleep", "infinity"]
