FROM rust:1.92-slim-bookworm

# 1. Dependencias del sistema 
RUN apt-get update && apt-get install -y \
    pkg-config libssl-dev build-essential g++ git wget curl ca-certificates gnupg \
    libffi-dev libbz2-dev libreadline-dev libsqlite3-dev zlib1g-dev \
    nodejs npm 

# 2. Cap'n Proto C++
RUN wget https://capnproto.org/capnproto-c++-1.3.0.tar.gz -O /tmp/capnproto.tar.gz && \
    cd /tmp && tar zxf capnproto.tar.gz && cd capnproto-c++-1.3.0 && \
    ./configure && make -j$(nproc) install && \
    rm -rf /tmp/capnproto.tar.gz /tmp/capnproto-c++-1.3.0

# 3. Java 25
RUN wget https://download.oracle.com/java/25/latest/jdk-25_linux-x64_bin.deb -O /tmp/jdk.deb && \
    apt-get install -y /tmp/jdk.deb && \
    rm /tmp/jdk.deb

# 4. Cap'n Proto Java RPC
RUN cd /tmp && \
    git clone https://github.com/vaci/capnproto-java-rpc.git && \
    cd capnproto-java-rpc && \
    make && make install && \
    rm -rf /tmp/capnproto-java-rpc

RUN cargo install cargo-tarpaulin

WORKDIR /app
CMD ["sleep", "infinity"]