// This file has been automatically generated by capnp-es.
import * as $ from "capnp-es";
export const _capnpFileId = BigInt("0xdf98f828a1c9751e");
export class TaxEngine_Calculate$Params extends $.Struct {
  static _capnp = {
    displayName: "calculate$Params",
    id: "df287cfc295e1dd1",
    size: new $.ObjectSize(0, 1),
  };
  _adoptTx(value) {
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownTx() {
    return $.utils.disown(this.tx);
  }
  get tx() {
    return $.utils.getStruct(0, TransactionRequest, this);
  }
  _hasTx() {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initTx() {
    return $.utils.initStructAt(0, TransactionRequest, this);
  }
  set tx(value) {
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  toString() { return "TaxEngine_Calculate$Params_" + super.toString(); }
}
export class TaxEngine_Calculate$Results extends $.Struct {
  static _capnp = {
    displayName: "calculate$Results",
    id: "99407d72449bd47f",
    size: new $.ObjectSize(0, 1),
  };
  _adoptResponse(value) {
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownResponse() {
    return $.utils.disown(this.response);
  }
  get response() {
    return $.utils.getStruct(0, TaxResponse, this);
  }
  _hasResponse() {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initResponse() {
    return $.utils.initStructAt(0, TaxResponse, this);
  }
  set response(value) {
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  toString() { return "TaxEngine_Calculate$Results_" + super.toString(); }
}
export class TaxEngine_Calculate$Results$Promise {
  pipeline;
  constructor(pipeline) {
    this.pipeline = pipeline;
  }
  async promise() {
    return await this.pipeline.struct();
  }
}
export class TaxEngine$Client {
  client;
  static interfaceId = BigInt("0x8fc1c2a51fbb3032");
  constructor(client) {
    this.client = client;
  }
  static methods = [
    {
      ParamsClass: TaxEngine_Calculate$Params,
      ResultsClass: TaxEngine_Calculate$Results,
      interfaceId: TaxEngine$Client.interfaceId,
      methodId: 0,
      interfaceName: "src/capnp/references.capnp:TaxEngine",
      methodName: "calculate"
    }
  ];
  calculate(paramsFunc) {
    const answer = this.client.call({
      method: TaxEngine$Client.methods[0],
      paramsFunc: paramsFunc
    });
    const pipeline = new $.Pipeline(TaxEngine_Calculate$Results, answer);
    return new TaxEngine_Calculate$Results$Promise(pipeline);
  }
}
$.Registry.register(TaxEngine$Client.interfaceId, TaxEngine$Client);
export class TaxEngine$Server extends $.Server {
  target;
  constructor(target) {
    super(target, [
      {
        ...TaxEngine$Client.methods[0],
        impl: target.calculate
      }
    ]);
    this.target = target;
  }
  client() {
    return new TaxEngine$Client(this);
  }
}
export class TaxEngine extends $.Interface {
  static Client = TaxEngine$Client;
  static Server = TaxEngine$Server;
  static _capnp = {
    displayName: "TaxEngine",
    id: "8fc1c2a51fbb3032",
    size: new $.ObjectSize(0, 0),
  };
  toString() { return "TaxEngine_" + super.toString(); }
}
export class TransactionRequest extends $.Struct {
  static _capnp = {
    displayName: "TransactionRequest",
    id: "c23dcff3cf4059cf",
    size: new $.ObjectSize(8, 3),
  };
  get clientId() {
    return $.utils.getText(0, this);
  }
  set clientId(value) {
    $.utils.setText(0, value, this);
  }
  get amount() {
    return $.utils.getFloat64(0, this);
  }
  set amount(value) {
    $.utils.setFloat64(0, value, this);
  }
  get jurisdiction() {
    return $.utils.getText(1, this);
  }
  set jurisdiction(value) {
    $.utils.setText(1, value, this);
  }
  get product() {
    return $.utils.getText(2, this);
  }
  set product(value) {
    $.utils.setText(2, value, this);
  }
  toString() { return "TransactionRequest_" + super.toString(); }
}
export class TaxResponse extends $.Struct {
  static _capnp = {
    displayName: "TaxResponse",
    id: "8299cac2fd7c3a14",
    size: new $.ObjectSize(8, 1),
  };
  static _Breakdown;
  get totalAmount() {
    return $.utils.getFloat64(0, this);
  }
  set totalAmount(value) {
    $.utils.setFloat64(0, value, this);
  }
  _adoptBreakdown(value) {
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownBreakdown() {
    return $.utils.disown(this.breakdown);
  }
  get breakdown() {
    return $.utils.getList(0, TaxResponse._Breakdown, this);
  }
  _hasBreakdown() {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initBreakdown(length) {
    return $.utils.initList(0, TaxResponse._Breakdown, length, this);
  }
  set breakdown(value) {
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  toString() { return "TaxResponse_" + super.toString(); }
}
export class TaxDetail extends $.Struct {
  static _capnp = {
    displayName: "TaxDetail",
    id: "9ce3cd2efb627b04",
    size: new $.ObjectSize(24, 1),
  };
  get taxType() {
    return $.utils.getText(0, this);
  }
  set taxType(value) {
    $.utils.setText(0, value, this);
  }
  get base() {
    return $.utils.getFloat64(0, this);
  }
  set base(value) {
    $.utils.setFloat64(0, value, this);
  }
  get rate() {
    return $.utils.getFloat64(8, this);
  }
  set rate(value) {
    $.utils.setFloat64(8, value, this);
  }
  get amount() {
    return $.utils.getFloat64(16, this);
  }
  set amount(value) {
    $.utils.setFloat64(16, value, this);
  }
  toString() { return "TaxDetail_" + super.toString(); }
}
TaxResponse._Breakdown = $.CompositeList(TaxDetail);
