// This file has been automatically generated by capnp-es.
import * as $ from "capnp-es";
export const _capnpFileId = BigInt("0xdf98f828a1c9751e");
export class TaxEngine_Calculate$Params extends $.Struct {
  static readonly _capnp = {
    displayName: "calculate$Params",
    id: "df287cfc295e1dd1",
    size: new $.ObjectSize(0, 1),
  };
  _adoptTx(value: $.Orphan<TransactionRequest>): void {
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownTx(): $.Orphan<TransactionRequest> {
    return $.utils.disown(this.tx);
  }
  get tx(): TransactionRequest {
    return $.utils.getStruct(0, TransactionRequest, this);
  }
  _hasTx(): boolean {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initTx(): TransactionRequest {
    return $.utils.initStructAt(0, TransactionRequest, this);
  }
  set tx(value: TransactionRequest) {
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  toString(): string { return "TaxEngine_Calculate$Params_" + super.toString(); }
}
export class TaxEngine_Calculate$Results extends $.Struct {
  static readonly _capnp = {
    displayName: "calculate$Results",
    id: "99407d72449bd47f",
    size: new $.ObjectSize(0, 1),
  };
  _adoptResponse(value: $.Orphan<TaxResponse>): void {
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownResponse(): $.Orphan<TaxResponse> {
    return $.utils.disown(this.response);
  }
  get response(): TaxResponse {
    return $.utils.getStruct(0, TaxResponse, this);
  }
  _hasResponse(): boolean {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initResponse(): TaxResponse {
    return $.utils.initStructAt(0, TaxResponse, this);
  }
  set response(value: TaxResponse) {
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  toString(): string { return "TaxEngine_Calculate$Results_" + super.toString(); }
}
export class TaxEngine_Calculate$Results$Promise {
  pipeline: $.Pipeline<any, any, TaxEngine_Calculate$Results>;
  constructor(pipeline: $.Pipeline<any, any, TaxEngine_Calculate$Results>) {
    this.pipeline = pipeline;
  }
  async promise(): Promise<TaxEngine_Calculate$Results> {
    return await this.pipeline.struct();
  }
}
export class TaxEngine$Client {
  client: $.Client;
  static readonly interfaceId: bigint = BigInt("0x8fc1c2a51fbb3032");
  constructor(client: $.Client) {
    this.client = client;
  }
  static readonly methods: [
    $.Method<TaxEngine_Calculate$Params, TaxEngine_Calculate$Results>
  ] = [
    {
      ParamsClass: TaxEngine_Calculate$Params,
      ResultsClass: TaxEngine_Calculate$Results,
      interfaceId: TaxEngine$Client.interfaceId,
      methodId: 0,
      interfaceName: "src/capnp/references.capnp:TaxEngine",
      methodName: "calculate"
    }
  ];
  calculate(paramsFunc?: (params: TaxEngine_Calculate$Params) => void): TaxEngine_Calculate$Results$Promise {
    const answer = this.client.call({
      method: TaxEngine$Client.methods[0],
      paramsFunc: paramsFunc
    });
    const pipeline = new $.Pipeline(TaxEngine_Calculate$Results, answer);
    return new TaxEngine_Calculate$Results$Promise(pipeline);
  }
}
$.Registry.register(TaxEngine$Client.interfaceId, TaxEngine$Client);
export interface TaxEngine$Server$Target {
  calculate(params: TaxEngine_Calculate$Params, results: TaxEngine_Calculate$Results): Promise<void>;
}
export class TaxEngine$Server extends $.Server {
  readonly target: TaxEngine$Server$Target;
  constructor(target: TaxEngine$Server$Target) {
    super(target, [
      {
        ...TaxEngine$Client.methods[0],
        impl: target.calculate
      }
    ]);
    this.target = target;
  }
  client(): TaxEngine$Client {
    return new TaxEngine$Client(this);
  }
}
export class TaxEngine extends $.Interface {
  static readonly Client = TaxEngine$Client;
  static readonly Server = TaxEngine$Server;
  static readonly _capnp = {
    displayName: "TaxEngine",
    id: "8fc1c2a51fbb3032",
    size: new $.ObjectSize(0, 0),
  };
  toString(): string { return "TaxEngine_" + super.toString(); }
}
export class TransactionRequest extends $.Struct {
  static readonly _capnp = {
    displayName: "TransactionRequest",
    id: "c23dcff3cf4059cf",
    size: new $.ObjectSize(8, 3),
  };
  get clientId(): string {
    return $.utils.getText(0, this);
  }
  set clientId(value: string) {
    $.utils.setText(0, value, this);
  }
  get amount(): number {
    return $.utils.getFloat64(0, this);
  }
  set amount(value: number) {
    $.utils.setFloat64(0, value, this);
  }
  get jurisdiction(): string {
    return $.utils.getText(1, this);
  }
  set jurisdiction(value: string) {
    $.utils.setText(1, value, this);
  }
  get product(): string {
    return $.utils.getText(2, this);
  }
  set product(value: string) {
    $.utils.setText(2, value, this);
  }
  toString(): string { return "TransactionRequest_" + super.toString(); }
}
export class TaxResponse extends $.Struct {
  static readonly _capnp = {
    displayName: "TaxResponse",
    id: "8299cac2fd7c3a14",
    size: new $.ObjectSize(8, 1),
  };
  static _Breakdown: $.ListCtor<TaxDetail>;
  get totalAmount(): number {
    return $.utils.getFloat64(0, this);
  }
  set totalAmount(value: number) {
    $.utils.setFloat64(0, value, this);
  }
  _adoptBreakdown(value: $.Orphan<$.List<TaxDetail>>): void {
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownBreakdown(): $.Orphan<$.List<TaxDetail>> {
    return $.utils.disown(this.breakdown);
  }
  get breakdown(): $.List<TaxDetail> {
    return $.utils.getList(0, TaxResponse._Breakdown, this);
  }
  _hasBreakdown(): boolean {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initBreakdown(length: number): $.List<TaxDetail> {
    return $.utils.initList(0, TaxResponse._Breakdown, length, this);
  }
  set breakdown(value: $.List<TaxDetail>) {
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  toString(): string { return "TaxResponse_" + super.toString(); }
}
export class TaxDetail extends $.Struct {
  static readonly _capnp = {
    displayName: "TaxDetail",
    id: "9ce3cd2efb627b04",
    size: new $.ObjectSize(24, 1),
  };
  get taxType(): string {
    return $.utils.getText(0, this);
  }
  set taxType(value: string) {
    $.utils.setText(0, value, this);
  }
  get base(): number {
    return $.utils.getFloat64(0, this);
  }
  set base(value: number) {
    $.utils.setFloat64(0, value, this);
  }
  get rate(): number {
    return $.utils.getFloat64(8, this);
  }
  set rate(value: number) {
    $.utils.setFloat64(8, value, this);
  }
  get amount(): number {
    return $.utils.getFloat64(16, this);
  }
  set amount(value: number) {
    $.utils.setFloat64(16, value, this);
  }
  toString(): string { return "TaxDetail_" + super.toString(); }
}
TaxResponse._Breakdown = $.CompositeList(TaxDetail);
